project        = "maxdrive"
region         = "us-west1"
todo_app_name  = "maxdrive"
todo_app_image = "royalt/maxdrive:latest"
service_run    = "run.googleapis.com"
role           = "roles/run.invoker"