name: 'Build todo app and push to the dockerhub'

on:
  push:
    branches: [ "feature/ci_cd_pipeline" ]
  pull_request:

permissions:
  contents: read

jobs:
  docker:
    name: 'Docker'
    runs-on: ubuntu-latest

    steps: 
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    #Docker install docker on the runner
    - name: Docker install
      uses: docker-practice/actions-setup-docker@master

    #Login to dockerhub
    - name: Docker login
      run: docker login -u=${{ vars.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}

    #Build the dockerfile
    - name: Docker build
      run: docker build . -t ${{ vars.DOCKER_USERNAME }}/maxdrive:todo

    #Push the dockerfile to dockerhub
    - name: Docker push
      run: docker push ${{ vars.DOCKER_USERNAME }}/maxdrive:todo

